# Generated by Django 5.2 on 2025-10-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_comments_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='body',
            new_name='comment',
        ),
    ]
